Region.create(name: "北海道")
Region.create(name: "東北")
Region.create(name: "関東")
Region.create(name: "中部")
Region.create(name: "近畿")
Region.create(name: "中国")
Region.create(name: "四国")
Region.create(name: "九州")

Prefecture.create(region_id: "1", name: "北海道")
Prefecture.create(region_id: "2", name: "青森県")
Prefecture.create(region_id: "2", name: "岩手県")
Prefecture.create(region_id: "2", name: "宮城県")
Prefecture.create(region_id: "2", name: "秋田県")
Prefecture.create(region_id: "2", name: "山形県")
Prefecture.create(region_id: "2", name: "福島県")
Prefecture.create(region_id: "3", name: "茨城県")
Prefecture.create(region_id: "3", name: "栃木県")
Prefecture.create(region_id: "3", name: "群馬県")
Prefecture.create(region_id: "3", name: "埼玉県")
Prefecture.create(region_id: "3", name: "千葉県")
Prefecture.create(region_id: "3", name: "東京都")
Prefecture.create(region_id: "3", name: "神奈川県")
Prefecture.create(region_id: "4", name: "新潟県")
Prefecture.create(region_id: "4", name: "富山県")
Prefecture.create(region_id: "4", name: "石川県")
Prefecture.create(region_id: "4", name: "福井県")
Prefecture.create(region_id: "4", name: "山梨県")
Prefecture.create(region_id: "4", name: "長野県")
Prefecture.create(region_id: "4", name: "岐阜県")
Prefecture.create(region_id: "4", name: "静岡県")
Prefecture.create(region_id: "4", name: "愛知県")
Prefecture.create(region_id: "5", name: "三重県")
Prefecture.create(region_id: "5", name: "滋賀県")
Prefecture.create(region_id: "5", name: "京都府")
Prefecture.create(region_id: "5", name: "大阪府")
Prefecture.create(region_id: "5", name: "兵庫県")
Prefecture.create(region_id: "5", name: "奈良県")
Prefecture.create(region_id: "5", name: "和歌山県")
Prefecture.create(region_id: "6", name: "鳥取県")
Prefecture.create(region_id: "6", name: "島根県")
Prefecture.create(region_id: "6", name: "岡山県")
Prefecture.create(region_id: "6", name: "広島県")
Prefecture.create(region_id: "6", name: "山口県")
Prefecture.create(region_id: "7", name: "徳島県")
Prefecture.create(region_id: "7", name: "香川県")
Prefecture.create(region_id: "7", name: "愛媛県")
Prefecture.create(region_id: "7", name: "高知県")
Prefecture.create(region_id: "8", name: "福岡県")
Prefecture.create(region_id: "8", name: "佐賀県")
Prefecture.create(region_id: "8", name: "長崎県")
Prefecture.create(region_id: "8", name: "熊本県")
Prefecture.create(region_id: "8", name: "大分県")
Prefecture.create(region_id: "8", name: "宮崎県")
Prefecture.create(region_id: "8", name: "鹿児島県")
Prefecture.create(region_id: "8", name: "沖縄県")

Area.create(prefecture_id: "28", name: "神戸市")
Area.create(prefecture_id: "28", name: "姫路市")
Area.create(prefecture_id: "28", name: "尼崎市")
Area.create(prefecture_id: "28", name: "明石市")
Area.create(prefecture_id: "28", name: "西宮市")
Area.create(prefecture_id: "28", name: "洲本市")
Area.create(prefecture_id: "28", name: "芦屋市")
Area.create(prefecture_id: "28", name: "相生市")
Area.create(prefecture_id: "28", name: "豊岡市")
Area.create(prefecture_id: "28", name: "加古川市")
Area.create(prefecture_id: "28", name: "赤穂市")
Area.create(prefecture_id: "28", name: "高砂市")
Area.create(prefecture_id: "28", name: "南あわじ市")
Area.create(prefecture_id: "28", name: "淡路市")
Area.create(prefecture_id: "28", name: "たつの市")
Area.create(prefecture_id: "28", name: "播磨町")
Area.create(prefecture_id: "28", name: "香美町")
Area.create(prefecture_id: "28", name: "新温泉町")

FishingMethod.create(name: "穴釣り")
FishingMethod.create(name: "サビキ釣り")
FishingMethod.create(name: "投げ釣り")

Species.create(name: "カサゴ")
Species.create(name: "キス")
Species.create(name: "メバル")
Species.create(name: "クロダイ")

TimeZone.create(time_zone: "早朝")
TimeZone.create(time_zone: "朝")
TimeZone.create(time_zone: "昼")
TimeZone.create(time_zone: "昼過ぎ")
TimeZone.create(time_zone: "夕方")
TimeZone.create(time_zone: "夜")
TimeZone.create(time_zone: "深夜")

Admin.create!(email: 'tsurireki@admin', password: 'tsurireki')